import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import VideoPlayer from "./components/videoPlayer";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Serjeel2 Video Player</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.main} ${inter.className}`}>
				<VideoPlayer
					url={
						"https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_30mb.mp4"
					}
				/>
			</main>
		</>
	);
}
